name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if needed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
